### ISSUE TITLE
Doesn't work with Blender 5

### ISSUE THREAD

**Issue by Mohammad9760** [sharpen3d/openvat#56]
produces the following error in Blender 5.0
`Python: Traceback (most recent call last):
  File "/home/mmd/.config/blender/5.0/extensions/user_default/openvat/operators.py", line 230, in execute
    core.setup_proxy_scene(obj, num_frames, width, height, num_wraps, temp_obj, pack_normals, frame_start)
  File "/home/mmd/.config/blender/5.0/extensions/user_default/openvat/core.py", line 120, in setup_proxy_scene
    setup_vat_scene(proxy_obj, obj.name, original_scene.name, num_frames, width, height, num_wraps, pack_normals)
  File "/home/mmd/.config/blender/5.0/extensions/user_default/openvat/core.py", line 237, in setup_vat_scene
    setup_compositing(vat_scene, output_dir, vat_scene.name, proxy_obj, image_format, fmt)
  File "/home/mmd/.config/blender/5.0/extensions/user_default/openvat/core.py", line 294, in setup_compositing
    tree = vat_scene.node_tree
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'node_tree'
`

**Comment by Mohammad9760** [comment]
I have used this addon in Blender 4.2 and it works.
but I will be upgrading to 5.2 in a couple of weeks when it's released.
let me know if you need any extra info

**Comment by hardboileduser** [comment]
Did not use it with v5.0 but it works on v5.1.x at least for me (OpenVAT v1.1.0)

v5.2 just released and I tried and it does not work with error:
```
Python: Traceback (most recent call last):
  File "/home/user/.config/blender/5.2/extensions/user_default/openvat/operators.py", line 160, in execute
    obj.modifiers[-1]["Socket_3"] = temp_obj
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
TypeError: bpy_struct[key] = val: id properties not supported for this type

**Comment by Mechitary** [comment]
@hardboileduser +1 have the same error on blender 5.2.0 LTS

edit: looks like this change in the 5.1.0 -> 5.2.0 changelog could be the issue: https://projects.blender.org/blender/blender/commit/1561c1ea4ab6

**Comment by dwarfmagic** [comment]
> [@hardboileduser](https://github.com/hardboileduser) +1 have the same error on blender 5.2.0 LTS
> 
> edit: looks like this change in the 5.1.0 -> 5.2.0 changelog could be the issue: https://projects.blender.org/blender/blender/commit/1561c1ea4ab6

I made a pull request: 
https://github.com/sharpen3d/openvat/pull/57

It is fixed on my end thanks to your linking that change. I was working on a project with Claude Code and this addon was recommended but didn't work for me because of the same LTS 5.2.0. I figured the overall addon wasn't too big so I let Claude munch on it and it got it fixed up with that referenced change. Figured I would share the rewrite with anyone who doesn't feel like burning tokens :)
