### ISSUE TITLE
AttributeError: 'Scene' object has no attribute 'node_tree' (Blender 5.0.0)

### ISSUE THREAD

**Issue by tgdflav** [sharpen3d/openvat#44]
Tried it out with Blender 5.0.0

```
Python: Traceback (most recent call last):
  File "...\AppData\Roaming\Blender Foundation\Blender\5.0\extensions\blender_org\openvat\operators.py", line 230, in execute
    core.setup_proxy_scene(obj, num_frames, width, height, num_wraps, temp_obj, pack_normals, frame_start)
  File "...\AppData\Roaming\Blender Foundation\Blender\5.0\extensions\blender_org\openvat\core.py", line 120, in setup_proxy_scene
    setup_vat_scene(proxy_obj, obj.name, original_scene.name, num_frames, width, height, num_wraps, pack_normals)
  File "...\AppData\Roaming\Blender Foundation\Blender\5.0\extensions\blender_org\openvat\core.py", line 237, in setup_vat_scene
    setup_compositing(vat_scene, output_dir, vat_scene.name, proxy_obj, image_format, fmt)
  File "...\AppData\Roaming\Blender Foundation\Blender\5.0\extensions\blender_org\openvat\core.py", line 294, in setup_compositing
    tree = vat_scene.node_tree
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'node_tree'
```

**Comment by p-7** [comment]
Yes, this error in on my test too …  not works in Blender 5.0

**Comment by sharpen3d** [comment]
Yep so this is just a compositor error with the new compositig changes in 5.0. Trying to pack in a couple other updates while I'm at it and be sure it's backwards compatible with 4.x. Should be available soon, I'll update this ticket when it's up.

**Comment by sharpen3d** [comment]
Updated for Blender 5.0 - pretty substantial update to catch all the changes here, I've tested a fair bit in 5.0 as well as ensuring backwards compatibility for Blender 4.x series -- Please report issues or let me know if anything breaks in the new version (1.1.0) 

You can update directly in Blender Via Extensions in Preferences, or grab the latest zip in the main repo
